const text = `The adult acorn woodpecker has a brownish-black head, back, wings and tail, white forehead, throat, belly and rump. The eyes are initially dark in fledglings, turning to white within a few months. There is a small part on the small of their backs where there are some greenish feathers. In most subspecies, adult males have a red cap starting at the forehead, whereas females have a black area between the forehead and the cap. The white neck, throat, and forehead patches are distinctive identifiers. When flying, they take a few flaps of their wings and drop a foot or so. White circles on their wings are visible when in flight. Acorn woodpeckers have a call that sounds almost like they are laughing. 

The acorn woodpecker's habitat is forested areas with oaks in the coastal areas and foothills of Oregon, California, and the southwestern United States, south through Central America to Colombia. This species may occur at low elevations in the north of its range, but rarely below 1,000 m (3,300 ft) in Central America, and it breeds up to the timberline. Nests are excavated in a cavity in a dead tree or a dead part of a tree. 

Acorn woodpeckers are cooperative breeders, living and breeding in family groups of up to 15 individuals. Field studies have shown that within the same population, groups range from monogamous pairs to polygynandrous breeding collectives consisting of coalitions of up to 8 males and 4 females, along with nonbreeding "helpers at the nest" that are offspring from prior breeding events. Regardless of composition, all breeder males (who are usually brothers or fathers and their sons) compete for matings with all breeder females (who are sisters or a mother and her daughter), the latter of which lay their eggs communally in the same nest cavity. There is considerable variability within and among populations, suggesting extraordinary social plasticity. Cooperative breeding, defined as more than two birds taking care of nestlings in the nest, is a relatively rare evolutionary trait that is thought to occur in only nine percent of bird species. Most cooperative breeding species have helpers at the nest, but acorn woodpeckers are unusual in exhibiting both helping at the nest and cooperative polygamy (polygynandry). It is generally believed that limited territories are a key driver of cooperative breeding behavior in birds, and in the case of the acorn woodpecker, the availability of acorn storage granaries (see Food and feeding) is a key limited resource.

Breeding coalitions consist of up to eight cobreeding males and up to four joint-nesting females. However, most nests consist of only a single breeder female and 1 to 3 cobreeder males. Nesting groups can also contain up to ten offspring helpers. As mentioned above, the breeder males are often brothers, and the females are usually sisters. However, reproductive vacancies—formed when all the breeders of one sex die—are filled by unrelated birds from elsewhere, so Inbreeding is rare, despite the high degree of relatedness among most group members.

In groups with more than one breeding female, the females put their eggs into a single nest cavity. A female usually destroys any eggs in the nest before she starts to lay. Once all the females start to lay, they stop removing eggs. Although multiple paternity and maternity are common within groups containing multiple cobreeders, no extra-group paternity has been detected. 

Acorn woodpeckers, as their name implies, depend heavily on acorns for food. Acorns are such an important resource to the California populations that acorn woodpeckers may nest in the fall to take advantage of the fall acorn crop, a rare behavior in birds. Acorns are stored in small holes drilled especially for this purpose in "granaries" or "storage trees"—usually snags, dead branches, utility poles, or wooden buildings. Storage holes—always in dead tissue such as bark or dead limbs—are used year after year, and granaries can consist of thousands of holes, each of which may be filled by an acorn in the autumn. Access to acorn crops influences the composition of acorn woodpecker communities. In one study in New Mexico, there were about 90% of non-breeding adults per social unit in 1976, a year of a poor acorn crop. The following year, 1977, there was a significant increase in acorn production and a correlating decrease in non-breeding adults per unit.

Although acorns are an important back-up food resource, acorn woodpeckers primarily feed on insects, sap, and fruit. They can be seen sallying from tree limbs to catch insects, eating fruit and seeds, and drilling holes to drink sap.

The woodpeckers then collect acorns and find a hole that is just the right size for the acorn. As acorns dry out, they are moved to smaller holes and granary maintenance requires a significant amount of the bird's time. The acorns are visible, and a group defends its granary against potential cache robbers like Steller's jays and western scrub-jays.

In some more tropical parts of its range the acorn woodpecker does not construct a "granary tree", but instead stores acorns in natural holes and cracks in bark. If the acorn crop is poor and birds cannot find enough to store, the woodpeckers will move to other areas over the winter. `;

export default text;
