const secretarybirdText = `The secretarybird or secretary bird (Sagittarius serpentarius) is a large, mostly terrestrial bird of prey. Endemic to Africa, it is usually found in the open grasslands and savanna of the sub-Saharan region. John Frederick Miller described the species in 1779. A member of the order Accipitriformes, which also includes many other diurnal birds of prey such as eagles, hawks, kites, vultures, and harriers, it is placed in its own family, Sagittariidae. 

The secretarybird is instantly recognizable as a very large bird with an eagle-like body on crane-like legs that give the bird a height of as much as 1.3 m (4 ft 3 in). The sexes are similar in appearance. Adults have a featherless red-orange face and predominantly grey plumage, with a flattened dark crest and black flight feathers and thighs.

Breeding can take place at any time of year, but tends to be late in the dry season. The nest is built at the top of a thorny tree, and a clutch of one to three eggs is laid. In years with plentiful food all three young can survive to fledging. The secretarybird hunts and catches prey on the ground, often stomping on victims to kill them. Insects and small vertebrates make up its diet. Prey

Although the secretarybird occurs over a large range, the results of localised surveys suggest that the total population is experiencing a rapid decline, probably as a result of habitat destruction. The species is therefore classed as Endangered by the International Union for Conservation of Nature. The secretarybird appears on the coats of arms of Sudan and South Africa. 

The Dutch naturalist Arnout Vosmaer described the secretarybird in 1769 on the basis of a live specimen that had been sent to Holland from the Cape of Good Hope two years earlier by an official of the Dutch East India Company. Vosmaer suggested that the species was called "sagittarius" by the Dutch settlers because its gait was thought to resemble an archer's. He also mentioned that it was known as the "secretarius" by farmers who had domesticated the bird to combat pests around their homesteads, and proposed that the word "secretarius" might be a corruption of "sagittarius". Ian Glenn of the University of the Free State suggests that Vosmaer's "sagittarius" is a misheard or mis-transcribed form of "secretarius", rather than the other way around.
Plate from John Frederick Miller's Icones animalium et plantarum, published 1779, with the original binomial name

In 1779 the English illustrator John Frederick Miller included a coloured plate of the secretarybird in his Icones animalium et plantarum and coined the binomial name Falco serpentarius. As the oldest published specific name, serpentarius has priority over later scientific names. The species was assigned to its own genus Sagittarius in 1783 by the French naturalist Johann Hermann in his Tabula affinitatum animalium. The generic name Sagittarius is Latin for "archer", and the specific epithet serpentarius is from Latin serpens meaning "serpent" or "snake". A second edition of Miller's plates was published in 1796 as Cimelia physica, with added text by English naturalist George Shaw, who named it Vultur serpentarius. The French naturalist Georges Cuvier erected the genus Serpentarius in 1798, and the German naturalist Johann Karl Wilhelm Illiger erected the (now synonymous) genus Gypogeranus from the Ancient Greek words gyps "vulture" and geranos "crane" in 1811.

In 1835 the Irish naturalist William Ogilby spoke at a meeting of the Zoological Society of London and proposed three species of secretarybird, distinguishing those from Senegambia as having broader crest feathers than those from South Africa, and reporting a distinct species from the Philippines based on the writings of Pierre Sonnerat in his Voyage à la Nouvelle-Guinée. There is no other evidence this taxon existed. Despite its large range, the secretarybird is considered monotypic: no subspecies are recognised.

The evolutionary relationship of the secretarybird to other raptors had long puzzled ornithologists. The species was usually placed in its own family Sagittariidae within the order Falconiformes. A large molecular phylogenetic study published in 2008 concluded that the secretarybird was sister to a clade containing the ospreys in the family Pandionidae and the kites, hawks and eagles in the family Accipitridae. The same study found that the falcons in the order Falconiformes were only distantly related to the other diurnal birds of prey. The families Cathartidae, Sagittariidae, Pandionidae and Accipitridae were therefore moved from Falconiformes to the resurrected Accipitriformes.[a] A later molecular phylogenetic study published in 2015 confirmed these relationships.

The earliest fossils associated with the family are two species from the genus Pelargopappus. The two species, from the Oligocene and Miocene respectively, were discovered in France. The feet in these fossils are more like those of the Accipitridae; it is suggested that these characteristics are primitive features within the family. In spite of their age, the two species are not thought to be ancestral to the secretarybird. Though strongly convergent with the modern secretarybird, the extinct raptor Apatosagittarius is thought to be an accipitrid.

The International Ornithologists' Union has designated "secretarybird" the official common name for the species. In 1780 the French polymath Georges-Louis Leclerc, Comte de Buffon suggested that the name secretary/secrétaire had been chosen because of the long quill-like feathers at the top of the bird's neck, reminiscent of a quill pen behind the ear of an ancient scribe. In 1977, C. Hilary Fry of Aberdeen University suggested that "secretary" is from the French secrétaire, a corruption of the Arabic صقر الطير saqr et-tair meaning either "hawk of the semi-desert" or "hawk that flies". Glenn has dismissed this etymology on the grounds that there is no evidence that the name came through French, instead supporting Buffon's etymology; namely, that the word comes from the Dutch secretaris "secretary", used by settlers in South Africa. 
`;

export default secretarybirdText;
